Exception on /admin/article [POST]
Traceback (most recent call last):
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jazpenn/coding/flask-blog/app/admin/views.py", line 61, in article
    user_id=current_user.id)
  File "<string>", line 4, in __init__
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/Users/jazpenn/coding/flask-blog/FBenv/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 649, in _declarative_constructor
    (k, cls_.__name__))
TypeError: 'title' is an invalid keyword argument for Article
